postgres: &postgres
  adapter: postgresql
  min_messages: warning

development:
  <<: *postgres
  database: testing_spree_shopify_importer_spree_development
test:
  <<: *postgres
  database: testing_spree_shopify_importer_spree_test
